In [2]:
import numpy as np

In [3]:
img_size = 256
x = np.linspace(-1, 1, img_size)
z = np.linspace(1, -1, img_size)
x, z = np.meshgrid(x, z)

mag = np.sqrt(x**2 + z**2)
valid = mag <=1
y = -np.sqrt(1 - (x*valid)**2 - (z*valid)**2)
x = x * valid
y = y * valid
z = z * valid
normal = np.concatenate((x[...,None], y[...,None], z[...,None]), axis=2)
normal = np.reshape(normal, (-1, 3))

In [20]:
for n in normal:
    if n[0] > 0:
        print(n)

[ 0.00392157 -0.12493751  0.99215686]
[ 0.01176471 -0.12444417  0.99215686]
[ 0.01960784 -0.12345158  0.99215686]
[ 0.02745098 -0.12194754  0.99215686]
[ 0.03529412 -0.11991282  0.99215686]
[ 0.04313725 -0.11731981  0.99215686]
[ 0.05098039 -0.11413045  0.99215686]
[ 0.05882353 -0.11029303  0.99215686]
[ 0.06666667 -0.10573701  0.99215686]
[ 0.0745098  -0.10036458  0.99215686]
[ 0.08235294 -0.09403591  0.99215686]
[ 0.09019608 -0.08654148  0.99215686]
[ 0.09803922 -0.077544    0.99215686]
[ 0.10588235 -0.06643559  0.99215686]
[ 0.11372549 -0.05187748  0.99215686]
[ 0.12156863 -0.02908313  0.99215686]
[ 0.00392157 -0.17638342  0.98431373]
[ 0.01176471 -0.17603432  0.98431373]
[ 0.01960784 -0.17533403  0.98431373]
[ 0.02745098 -0.17427832  0.98431373]
[ 0.03529412 -0.17286068  0.98431373]
[ 0.04313725 -0.17107211  0.98431373]
[ 0.05098039 -0.16890083  0.98431373]
[ 0.05882353 -0.16633184  0.98431373]
[ 0.06666667 -0.1633464   0.98431373]
[ 0.0745098  -0.15992116  0.98431373]
[ 0.08235294

[ 0.5372549  -0.19899787  0.81960784]
[ 0.54509804 -0.17638342  0.81960784]
[ 0.55294118 -0.1499968   0.81960784]
[ 0.56078431 -0.11731981  0.81960784]
[ 0.56862745 -0.07004146  0.81960784]
[ 0.00392157 -0.58397147  0.81176471]
[ 0.01176471 -0.58386613  0.81176471]
[ 0.01960784 -0.58365537  0.81176471]
[ 0.02745098 -0.5833391   0.81176471]
[ 0.03529412 -0.58291714  0.81176471]
[ 0.04313725 -0.58238925  0.81176471]
[ 0.05098039 -0.58175516  0.81176471]
[ 0.05882353 -0.5810145   0.81176471]
[ 0.06666667 -0.58016689  0.81176471]
[ 0.0745098  -0.57921184  0.81176471]
[ 0.08235294 -0.57814882  0.81176471]
[ 0.09019608 -0.57697724  0.81176471]
[ 0.09803922 -0.57569643  0.81176471]
[ 0.10588235 -0.57430566  0.81176471]
[ 0.11372549 -0.57280413  0.81176471]
[ 0.12156863 -0.57119098  0.81176471]
[ 0.12941176 -0.56946524  0.81176471]
[ 0.1372549  -0.56762589  0.81176471]
[ 0.14509804 -0.56567183  0.81176471]
[ 0.15294118 -0.56360186  0.81176471]
[ 0.16078431 -0.5614147   0.81176471]
[ 0.16862745

[ 0.10588235 -0.71959449  0.68627451]
[ 0.11372549 -0.71839669  0.68627451]
[ 0.12156863 -0.71711113  0.68627451]
[ 0.12941176 -0.71573731  0.68627451]
[ 0.1372549  -0.71427473  0.68627451]
[ 0.14509804 -0.71272285  0.68627451]
[ 0.15294118 -0.71108107  0.68627451]
[ 0.16078431 -0.70934879  0.68627451]
[ 0.16862745 -0.70752532  0.68627451]
[ 0.17647059 -0.70560997  0.68627451]
[ 0.18431373 -0.70360198  0.68627451]
[ 0.19215686 -0.70150056  0.68627451]
[ 0.2        -0.69930487  0.68627451]
[ 0.20784314 -0.69701401  0.68627451]
[ 0.21568627 -0.69462704  0.68627451]
[ 0.22352941 -0.69214298  0.68627451]
[ 0.23137255 -0.68956076  0.68627451]
[ 0.23921569 -0.68687929  0.68627451]
[ 0.24705882 -0.68409739  0.68627451]
[ 0.25490196 -0.68121383  0.68627451]
[ 0.2627451  -0.67822733  0.68627451]
[ 0.27058824 -0.67513651  0.68627451]
[ 0.27843137 -0.67193993  0.68627451]
[ 0.28627451 -0.66863608  0.68627451]
[ 0.29411765 -0.66522335  0.68627451]
[ 0.30196078 -0.66170007  0.68627451]
[ 0.30980392

[ 0.16078431 -0.80114297  0.57647059]
[ 0.16862745 -0.79952889  0.57647059]
[ 0.17647059 -0.79783444  0.57647059]
[ 0.18431373 -0.79605911  0.57647059]
[ 0.19215686 -0.79420237  0.57647059]
[ 0.2        -0.79226363  0.57647059]
[ 0.20784314 -0.7902423   0.57647059]
[ 0.21568627 -0.78813774  0.57647059]
[ 0.22352941 -0.78594928  0.57647059]
[ 0.23137255 -0.78367621  0.57647059]
[ 0.23921569 -0.78131781  0.57647059]
[ 0.24705882 -0.77887329  0.57647059]
[ 0.25490196 -0.77634184  0.57647059]
[ 0.2627451  -0.77372261  0.57647059]
[ 0.27058824 -0.7710147   0.57647059]
[ 0.27843137 -0.76821718  0.57647059]
[ 0.28627451 -0.76532906  0.57647059]
[ 0.29411765 -0.76234931  0.57647059]
[ 0.30196078 -0.75927686  0.57647059]
[ 0.30980392 -0.75611057  0.57647059]
[ 0.31764706 -0.75284926  0.57647059]
[ 0.3254902  -0.74949169  0.57647059]
[ 0.33333333 -0.74603656  0.57647059]
[ 0.34117647 -0.74248251  0.57647059]
[ 0.34901961 -0.73882811  0.57647059]
[ 0.35686275 -0.73507186  0.57647059]
[ 0.36470588

[ 0.49803922 -0.72061958  0.48235294]
[ 0.50588235 -0.71513543  0.48235294]
[ 0.51372549 -0.70952221  0.48235294]
[ 0.52156863 -0.70377682  0.48235294]
[ 0.52941176 -0.697896    0.48235294]
[ 0.5372549  -0.6918763   0.48235294]
[ 0.54509804 -0.68571406  0.48235294]
[ 0.55294118 -0.6794054   0.48235294]
[ 0.56078431 -0.6729462   0.48235294]
[ 0.56862745 -0.6663321   0.48235294]
[ 0.57647059 -0.65955841  0.48235294]
[ 0.58431373 -0.65262019  0.48235294]
[ 0.59215686 -0.64551211  0.48235294]
[ 0.6        -0.63822852  0.48235294]
[ 0.60784314 -0.63076332  0.48235294]
[ 0.61568627 -0.62310998  0.48235294]
[ 0.62352941 -0.6152615   0.48235294]
[ 0.63137255 -0.6072103   0.48235294]
[ 0.63921569 -0.5989482   0.48235294]
[ 0.64705882 -0.59046636  0.48235294]
[ 0.65490196 -0.58175516  0.48235294]
[ 0.6627451  -0.57280413  0.48235294]
[ 0.67058824 -0.56360186  0.48235294]
[ 0.67843137 -0.55413583  0.48235294]
[ 0.68627451 -0.54439226  0.48235294]
[ 0.69411765 -0.534356    0.48235294]
[ 0.70196078

[ 0.61568627 -0.68571406  0.38823529]
[ 0.62352941 -0.67859003  0.38823529]
[ 0.63137255 -0.67129879  0.38823529]
[ 0.63921569 -0.66383482  0.38823529]
[ 0.64705882 -0.65619222  0.38823529]
[ 0.65490196 -0.6483647   0.38823529]
[ 0.6627451  -0.64034545  0.38823529]
[ 0.67058824 -0.63212718  0.38823529]
[ 0.67843137 -0.62370204  0.38823529]
[ 0.68627451 -0.6150615   0.38823529]
[ 0.69411765 -0.60619638  0.38823529]
[ 0.70196078 -0.59709665  0.38823529]
[ 0.70980392 -0.58775143  0.38823529]
[ 0.71764706 -0.57814882  0.38823529]
[ 0.7254902  -0.56827575  0.38823529]
[ 0.73333333 -0.55811789  0.38823529]
[ 0.74117647 -0.54765938  0.38823529]
[ 0.74901961 -0.53688265  0.38823529]
[ 0.75686275 -0.52576814  0.38823529]
[ 0.76470588 -0.51429395  0.38823529]
[ 0.77254902 -0.50243544  0.38823529]
[ 0.78039216 -0.4901647   0.38823529]
[ 0.78823529 -0.47744997  0.38823529]
[ 0.79607843 -0.46425477  0.38823529]
[ 0.80392157 -0.45053687  0.38823529]
[ 0.81176471 -0.43624697  0.38823529]
[ 0.81960784

[ 0.21568627 -0.93111452  0.29411765]
[ 0.22352941 -0.92926283  0.29411765]
[ 0.23137255 -0.92734112  0.29411765]
[ 0.23921569 -0.92534894  0.29411765]
[ 0.24705882 -0.92328584  0.29411765]
[ 0.25490196 -0.92115134  0.29411765]
[ 0.2627451  -0.91894495  0.29411765]
[ 0.27058824 -0.91666614  0.29411765]
[ 0.27843137 -0.91431438  0.29411765]
[ 0.28627451 -0.91188909  0.29411765]
[ 0.29411765 -0.9093897   0.29411765]
[ 0.30196078 -0.90681558  0.29411765]
[ 0.30980392 -0.9041661   0.29411765]
[ 0.31764706 -0.9014406   0.29411765]
[ 0.3254902  -0.89863838  0.29411765]
[ 0.33333333 -0.89575873  0.29411765]
[ 0.34117647 -0.89280089  0.29411765]
[ 0.34901961 -0.88976408  0.29411765]
[ 0.35686275 -0.8866475   0.29411765]
[ 0.36470588 -0.8834503   0.29411765]
[ 0.37254902 -0.8801716   0.29411765]
[ 0.38039216 -0.87681048  0.29411765]
[ 0.38823529 -0.873366    0.29411765]
[ 0.39607843 -0.86983716  0.29411765]
[ 0.40392157 -0.86622294  0.29411765]
[ 0.41176471 -0.86252225  0.29411765]
[ 0.41960784

[ 0.41176471 -0.88727169  0.20784314]
[ 0.41960784 -0.88358955  0.20784314]
[ 0.42745098 -0.87982208  0.20784314]
[ 0.43529412 -0.87596819  0.20784314]
[ 0.44313725 -0.87202672  0.20784314]
[ 0.45098039 -0.8679965   0.20784314]
[ 0.45882353 -0.86387626  0.20784314]
[ 0.46666667 -0.85966473  0.20784314]
[ 0.4745098  -0.85536055  0.20784314]
[ 0.48235294 -0.85096232  0.20784314]
[ 0.49019608 -0.84646857  0.20784314]
[ 0.49803922 -0.84187776  0.20784314]
[ 0.50588235 -0.83718832  0.20784314]
[ 0.51372549 -0.83239855  0.20784314]
[ 0.52156863 -0.82750674  0.20784314]
[ 0.52941176 -0.82251104  0.20784314]
[ 0.5372549  -0.81740957  0.20784314]
[ 0.54509804 -0.81220032  0.20784314]
[ 0.55294118 -0.80688121  0.20784314]
[ 0.56078431 -0.80145005  0.20784314]
[ 0.56862745 -0.79590455  0.20784314]
[ 0.57647059 -0.7902423   0.20784314]
[ 0.58431373 -0.78446077  0.20784314]
[ 0.59215686 -0.77855731  0.20784314]
[ 0.6        -0.77252911  0.20784314]
[ 0.60784314 -0.76637325  0.20784314]
[ 0.61568627

[ 0.49019608 -0.86309262  0.12156863]
[ 0.49803922 -0.85859071  0.12156863]
[ 0.50588235 -0.85399304  0.12156863]
[ 0.51372549 -0.84929806  0.12156863]
[ 0.52156863 -0.84450414  0.12156863]
[ 0.52941176 -0.83960958  0.12156863]
[ 0.5372549  -0.83461263  0.12156863]
[ 0.54509804 -0.82951142  0.12156863]
[ 0.55294118 -0.82430402  0.12156863]
[ 0.56078431 -0.81898841  0.12156863]
[ 0.56862745 -0.81356247  0.12156863]
[ 0.57647059 -0.80802397  0.12156863]
[ 0.58431373 -0.80237057  0.12156863]
[ 0.59215686 -0.79659985  0.12156863]
[ 0.6        -0.79070922  0.12156863]
[ 0.60784314 -0.78469599  0.12156863]
[ 0.61568627 -0.77855731  0.12156863]
[ 0.62352941 -0.77229019  0.12156863]
[ 0.63137255 -0.76589149  0.12156863]
[ 0.63921569 -0.75935787  0.12156863]
[ 0.64705882 -0.75268582  0.12156863]
[ 0.65490196 -0.74587163  0.12156863]
[ 0.6627451  -0.73891136  0.12156863]
[ 0.67058824 -0.73180085  0.12156863]
[ 0.67843137 -0.72453567  0.12156863]
[ 0.68627451 -0.71711113  0.12156863]
[ 0.69411765

[ 0.22352941 -0.97374215  0.04313725]
[ 0.23137255 -0.97190839  0.04313725]
[ 0.23921569 -0.97000775  0.04313725]
[ 0.24705882 -0.96803983  0.04313725]
[ 0.25490196 -0.96600423  0.04313725]
[ 0.2627451  -0.96390051  0.04313725]
[ 0.27058824 -0.96172823  0.04313725]
[ 0.27843137 -0.95948692  0.04313725]
[ 0.28627451 -0.9571761   0.04313725]
[ 0.29411765 -0.95479526  0.04313725]
[ 0.30196078 -0.95234388  0.04313725]
[ 0.30980392 -0.94982141  0.04313725]
[ 0.31764706 -0.94722728  0.04313725]
[ 0.3254902  -0.94456091  0.04313725]
[ 0.33333333 -0.94182167  0.04313725]
[ 0.34117647 -0.93900894  0.04313725]
[ 0.34901961 -0.93612205  0.04313725]
[ 0.35686275 -0.93316031  0.04313725]
[ 0.36470588 -0.930123    0.04313725]
[ 0.37254902 -0.92700939  0.04313725]
[ 0.38039216 -0.9238187   0.04313725]
[ 0.38823529 -0.92055013  0.04313725]
[ 0.39607843 -0.91720284  0.04313725]
[ 0.40392157 -0.91377598  0.04313725]
[ 0.41176471 -0.91026864  0.04313725]
[ 0.41960784 -0.9066799   0.04313725]
[ 0.42745098

[ 0.76470588 -0.64341218 -0.03529412]
[ 0.77254902 -0.63397345 -0.03529412]
[ 0.78039216 -0.62429353 -0.03529412]
[ 0.78823529 -0.61436101 -0.03529412]
[ 0.79607843 -0.60416344 -0.03529412]
[ 0.80392157 -0.59368715 -0.03529412]
[ 0.81176471 -0.58291714 -0.03529412]
[ 0.81960784 -0.57183679 -0.03529412]
[ 0.82745098 -0.56042769 -0.03529412]
[ 0.83529412 -0.54866936 -0.03529412]
[ 0.84313725 -0.53653881 -0.03529412]
[ 0.85098039 -0.52401021 -0.03529412]
[ 0.85882353 -0.51105427 -0.03529412]
[ 0.86666667 -0.49763763 -0.03529412]
[ 0.8745098  -0.48372195 -0.03529412]
[ 0.88235294 -0.46926284 -0.03529412]
[ 0.89019608 -0.4542084  -0.03529412]
[ 0.89803922 -0.43849731 -0.03529412]
[ 0.90588235 -0.42205626 -0.03529412]
[ 0.91372549 -0.40479631 -0.03529412]
[ 0.92156863 -0.3866078  -0.03529412]
[ 0.92941176 -0.36735282 -0.03529412]
[ 0.9372549  -0.34685382 -0.03529412]
[ 0.94509804 -0.32487539 -0.03529412]
[ 0.95294118 -0.30109374 -0.03529412]
[ 0.96078431 -0.2750415  -0.03529412]
[ 0.96862745

[ 0.2        -0.9722248  -0.12156863]
[ 0.20784314 -0.97057833 -0.12156863]
[ 0.21568627 -0.96886557 -0.12156863]
[ 0.22352941 -0.96708618 -0.12156863]
[ 0.23137255 -0.96523977 -0.12156863]
[ 0.23921569 -0.96332597 -0.12156863]
[ 0.24705882 -0.96134437 -0.12156863]
[ 0.25490196 -0.95929456 -0.12156863]
[ 0.2627451  -0.9571761  -0.12156863]
[ 0.27058824 -0.95498852 -0.12156863]
[ 0.27843137 -0.95273136 -0.12156863]
[ 0.28627451 -0.95040411 -0.12156863]
[ 0.29411765 -0.94800627 -0.12156863]
[ 0.30196078 -0.94553728 -0.12156863]
[ 0.30980392 -0.94299661 -0.12156863]
[ 0.31764706 -0.94038365 -0.12156863]
[ 0.3254902  -0.93769782 -0.12156863]
[ 0.33333333 -0.93493848 -0.12156863]
[ 0.34117647 -0.93210498 -0.12156863]
[ 0.34901961 -0.92919663 -0.12156863]
[ 0.35686275 -0.92621275 -0.12156863]
[ 0.36470588 -0.92315258 -0.12156863]
[ 0.37254902 -0.92001538 -0.12156863]
[ 0.38039216 -0.91680035 -0.12156863]
[ 0.38823529 -0.91350666 -0.12156863]
[ 0.39607843 -0.91013348 -0.12156863]
[ 0.40392157

[ 0.31764706 -0.92687666 -0.2       ]
[ 0.3254902  -0.92415157 -0.2       ]
[ 0.33333333 -0.92135166 -0.2       ]
[ 0.34117647 -0.91847625 -0.2       ]
[ 0.34901961 -0.91552461 -0.2       ]
[ 0.35686275 -0.91249602 -0.2       ]
[ 0.36470588 -0.9093897  -0.2       ]
[ 0.37254902 -0.90620485 -0.2       ]
[ 0.38039216 -0.90294064 -0.2       ]
[ 0.38823529 -0.89959622 -0.2       ]
[ 0.39607843 -0.89617067 -0.2       ]
[ 0.40392157 -0.89266308 -0.2       ]
[ 0.41176471 -0.88907245 -0.2       ]
[ 0.41960784 -0.8853978  -0.2       ]
[ 0.42745098 -0.88163805 -0.2       ]
[ 0.43529412 -0.87779213 -0.2       ]
[ 0.44313725 -0.8738589  -0.2       ]
[ 0.45098039 -0.86983716 -0.2       ]
[ 0.45882353 -0.86572569 -0.2       ]
[ 0.46666667 -0.8615232  -0.2       ]
[ 0.4745098  -0.85722835 -0.2       ]
[ 0.48235294 -0.85283975 -0.2       ]
[ 0.49019608 -0.84835594 -0.2       ]
[ 0.49803922 -0.84377541 -0.2       ]
[ 0.50588235 -0.83909656 -0.2       ]
[ 0.51372549 -0.83431776 -0.2       ]
[ 0.52156863

[ 0.41176471 -0.86515706 -0.28627451]
[ 0.41960784 -0.86138038 -0.28627451]
[ 0.42745098 -0.85751534 -0.28627451]
[ 0.43529412 -0.85356074 -0.28627451]
[ 0.44313725 -0.84951532 -0.28627451]
[ 0.45098039 -0.84537778 -0.28627451]
[ 0.45882353 -0.84114676 -0.28627451]
[ 0.46666667 -0.83682085 -0.28627451]
[ 0.4745098  -0.83239855 -0.28627451]
[ 0.48235294 -0.82787834 -0.28627451]
[ 0.49019608 -0.82325859 -0.28627451]
[ 0.49803922 -0.81853763 -0.28627451]
[ 0.50588235 -0.81371368 -0.28627451]
[ 0.51372549 -0.80878491 -0.28627451]
[ 0.52156863 -0.80374938 -0.28627451]
[ 0.52941176 -0.79860509 -0.28627451]
[ 0.5372549  -0.79334991 -0.28627451]
[ 0.54509804 -0.78798162 -0.28627451]
[ 0.55294118 -0.7824979  -0.28627451]
[ 0.56078431 -0.7768963  -0.28627451]
[ 0.56862745 -0.77117425 -0.28627451]
[ 0.57647059 -0.76532906 -0.28627451]
[ 0.58431373 -0.75935787 -0.28627451]
[ 0.59215686 -0.75325769 -0.28627451]
[ 0.6        -0.74702537 -0.28627451]
[ 0.60784314 -0.74065756 -0.28627451]
[ 0.61568627

[ 0.00392157 -0.92800423 -0.37254902]
[ 0.01176471 -0.92793794 -0.37254902]
[ 0.01960784 -0.92780535 -0.37254902]
[ 0.02745098 -0.92760642 -0.37254902]
[ 0.03529412 -0.92734112 -0.37254902]
[ 0.04313725 -0.92700939 -0.37254902]
[ 0.05098039 -0.92661115 -0.37254902]
[ 0.05882353 -0.92614633 -0.37254902]
[ 0.06666667 -0.92561481 -0.37254902]
[ 0.0745098  -0.9250165  -0.37254902]
[ 0.08235294 -0.92435124 -0.37254902]
[ 0.09019608 -0.92361891 -0.37254902]
[ 0.09803922 -0.92281934 -0.37254902]
[ 0.10588235 -0.92195236 -0.37254902]
[ 0.11372549 -0.92101777 -0.37254902]
[ 0.12156863 -0.92001538 -0.37254902]
[ 0.12941176 -0.91894495 -0.37254902]
[ 0.1372549  -0.91780625 -0.37254902]
[ 0.14509804 -0.91659903 -0.37254902]
[ 0.15294118 -0.91532302 -0.37254902]
[ 0.16078431 -0.91397792 -0.37254902]
[ 0.16862745 -0.91256343 -0.37254902]
[ 0.17647059 -0.91107923 -0.37254902]
[ 0.18431373 -0.90952497 -0.37254902]
[ 0.19215686 -0.90790031 -0.37254902]
[ 0.2        -0.90620485 -0.37254902]
[ 0.20784314

[ 0.83529412 -0.3029269  -0.45882353]
[ 0.84313725 -0.28035788 -0.45882353]
[ 0.85098039 -0.25556475 -0.45882353]
[ 0.85882353 -0.22782255 -0.45882353]
[ 0.86666667 -0.19588225 -0.45882353]
[ 0.8745098  -0.15720551 -0.45882353]
[ 0.88235294 -0.10456699 -0.45882353]
[ 0.00392157 -0.88442458 -0.46666667]
[ 0.01176471 -0.88435503 -0.46666667]
[ 0.01960784 -0.8842159  -0.46666667]
[ 0.02745098 -0.88400716 -0.46666667]
[ 0.03529412 -0.88372877 -0.46666667]
[ 0.04313725 -0.88338067 -0.46666667]
[ 0.05098039 -0.88296275 -0.46666667]
[ 0.05882353 -0.88247494 -0.46666667]
[ 0.06666667 -0.8819171  -0.46666667]
[ 0.0745098  -0.88128912 -0.46666667]
[ 0.08235294 -0.88059083 -0.46666667]
[ 0.09019608 -0.87982208 -0.46666667]
[ 0.09803922 -0.87898267 -0.46666667]
[ 0.10588235 -0.87807241 -0.46666667]
[ 0.11372549 -0.87709106 -0.46666667]
[ 0.12156863 -0.87603841 -0.46666667]
[ 0.12941176 -0.87491418 -0.46666667]
[ 0.1372549  -0.8737181  -0.46666667]
[ 0.14509804 -0.87244987 -0.46666667]
[ 0.15294118

[ 0.57647059 -0.59430852 -0.56078431]
[ 0.58431373 -0.58659903 -0.56078431]
[ 0.59215686 -0.57868057 -0.56078431]
[ 0.6        -0.57054444 -0.56078431]
[ 0.60784314 -0.56218118 -0.56078431]
[ 0.61568627 -0.5535805  -0.56078431]
[ 0.62352941 -0.54473115 -0.56078431]
[ 0.63137255 -0.53562082 -0.56078431]
[ 0.63921569 -0.52623594 -0.56078431]
[ 0.64705882 -0.51656155 -0.56078431]
[ 0.65490196 -0.50658106 -0.56078431]
[ 0.6627451  -0.49627602 -0.56078431]
[ 0.67058824 -0.48562575 -0.56078431]
[ 0.67843137 -0.47460702 -0.56078431]
[ 0.68627451 -0.46319353 -0.56078431]
[ 0.69411765 -0.45135534 -0.56078431]
[ 0.70196078 -0.43905809 -0.56078431]
[ 0.70980392 -0.42626206 -0.56078431]
[ 0.71764706 -0.41292088 -0.56078431]
[ 0.7254902  -0.39897986 -0.56078431]
[ 0.73333333 -0.38437374 -0.56078431]
[ 0.74117647 -0.36902357 -0.56078431]
[ 0.74901961 -0.35283223 -0.56078431]
[ 0.75686275 -0.33567803 -0.56078431]
[ 0.76470588 -0.31740489 -0.56078431]
[ 0.77254902 -0.29780693 -0.56078431]
[ 0.78039216

[ 0.29411765 -0.68103321 -0.67058824]
[ 0.30196078 -0.67759214 -0.67058824]
[ 0.30980392 -0.67404225 -0.67058824]
[ 0.31764706 -0.67038181 -0.67058824]
[ 0.3254902  -0.66660899 -0.67058824]
[ 0.33333333 -0.66272189 -0.67058824]
[ 0.34117647 -0.65871848 -0.67058824]
[ 0.34901961 -0.65459662 -0.67058824]
[ 0.35686275 -0.65035406 -0.67058824]
[ 0.36470588 -0.64598842 -0.67058824]
[ 0.37254902 -0.64149719 -0.67058824]
[ 0.38039216 -0.63687772 -0.67058824]
[ 0.38823529 -0.63212718 -0.67058824]
[ 0.39607843 -0.62724261 -0.67058824]
[ 0.40392157 -0.62222085 -0.67058824]
[ 0.41176471 -0.61705854 -0.67058824]
[ 0.41960784 -0.61175214 -0.67058824]
[ 0.42745098 -0.60629785 -0.67058824]
[ 0.43529412 -0.60069164 -0.67058824]
[ 0.44313725 -0.59492923 -0.67058824]
[ 0.45098039 -0.58900603 -0.67058824]
[ 0.45882353 -0.58291714 -0.67058824]
[ 0.46666667 -0.5766573  -0.67058824]
[ 0.4745098  -0.57022089 -0.67058824]
[ 0.48235294 -0.56360186 -0.67058824]
[ 0.49019608 -0.5567937  -0.67058824]
[ 0.49803922

[ 0.03529412 -0.61436101 -0.78823529]
[ 0.04313725 -0.61386016 -0.78823529]
[ 0.05098039 -0.61325861 -0.78823529]
[ 0.05882353 -0.61255605 -0.78823529]
[ 0.06666667 -0.61175214 -0.78823529]
[ 0.0745098  -0.61084647 -0.78823529]
[ 0.08235294 -0.6098386  -0.78823529]
[ 0.09019608 -0.60872801 -0.78823529]
[ 0.09803922 -0.60751414 -0.78823529]
[ 0.10588235 -0.60619638 -0.78823529]
[ 0.11372549 -0.60477404 -0.78823529]
[ 0.12156863 -0.60324638 -0.78823529]
[ 0.12941176 -0.6016126  -0.78823529]
[ 0.1372549  -0.59987183 -0.78823529]
[ 0.14509804 -0.59802314 -0.78823529]
[ 0.15294118 -0.59606553 -0.78823529]
[ 0.16078431 -0.59399792 -0.78823529]
[ 0.16862745 -0.59181915 -0.78823529]
[ 0.17647059 -0.58952799 -0.78823529]
[ 0.18431373 -0.58712313 -0.78823529]
[ 0.19215686 -0.58460317 -0.78823529]
[ 0.2        -0.5819666  -0.78823529]
[ 0.20784314 -0.57921184 -0.78823529]
[ 0.21568627 -0.57633719 -0.78823529]
[ 0.22352941 -0.57334084 -0.78823529]
[ 0.23137255 -0.57022089 -0.78823529]
[ 0.23921569

[ 0.12941176 -0.32373731 -0.9372549 ]
[ 0.1372549  -0.32049078 -0.9372549 ]
[ 0.14509804 -0.31701705 -0.9372549 ]
[ 0.15294118 -0.31330855 -0.9372549 ]
[ 0.16078431 -0.30935684 -0.9372549 ]
[ 0.16862745 -0.30515247 -0.9372549 ]
[ 0.17647059 -0.30068485 -0.9372549 ]
[ 0.18431373 -0.29594205 -0.9372549 ]
[ 0.19215686 -0.29091062 -0.9372549 ]
[ 0.2        -0.28557529 -0.9372549 ]
[ 0.20784314 -0.2799187  -0.9372549 ]
[ 0.21568627 -0.27392094 -0.9372549 ]
[ 0.22352941 -0.26755906 -0.9372549 ]
[ 0.23137255 -0.26080643 -0.9372549 ]
[ 0.23921569 -0.25363183 -0.9372549 ]
[ 0.24705882 -0.24599835 -0.9372549 ]
[ 0.25490196 -0.23786181 -0.9372549 ]
[ 0.2627451  -0.22916863 -0.9372549 ]
[ 0.27058824 -0.2198528  -0.9372549 ]
[ 0.27843137 -0.20983141 -0.9372549 ]
[ 0.28627451 -0.19899787 -0.9372549 ]
[ 0.29411765 -0.18721127 -0.9372549 ]
[ 0.30196078 -0.17427832 -0.9372549 ]
[ 0.30980392 -0.15992116 -0.9372549 ]
[ 0.31764706 -0.14371359 -0.9372549 ]
[ 0.3254902  -0.12493751 -0.9372549 ]
[ 0.33333333

In [27]:
def mag(arr):
    return np.sqrt(arr[0]**2 + arr[1]**2 + arr[2]**2)

mag([0.2 ,       -0.14751563,  0.96862745])

0.9999999989938996

In [14]:
def SH_basis(normal):
    '''
        get SH basis based on normal
        normal is a Nx3 matrix
        return a Nx9 matrix
        The order of SH here is:
        1, Y, Z, X, YX, YZ, 3Z^2-1, XZ, X^2-y^2
    '''
    numElem = normal.shape[0]

    norm_X = normal[:,0]
    norm_Y = normal[:,1]
    norm_Z = normal[:,2]

    sh_basis = np.zeros((numElem, 9))
    att= np.pi*np.array([1, 2.0/3.0, 1/4.0])
    sh_basis[:,0] = 0.5/np.sqrt(np.pi)*att[0]

    sh_basis[:,1] = np.sqrt(3)/2/np.sqrt(np.pi)*norm_Y*att[1]
    sh_basis[:,2] = np.sqrt(3)/2/np.sqrt(np.pi)*norm_Z*att[1]
    sh_basis[:,3] = np.sqrt(3)/2/np.sqrt(np.pi)*norm_X*att[1]

    sh_basis[:,4] = np.sqrt(15)/2/np.sqrt(np.pi)*norm_Y*norm_X*att[2]
    sh_basis[:,5] = np.sqrt(15)/2/np.sqrt(np.pi)*norm_Y*norm_Z*att[2]
    sh_basis[:,6] = np.sqrt(5)/4/np.sqrt(np.pi)*(3*norm_Z**2-1)*att[2]
    sh_basis[:,7] = np.sqrt(15)/2/np.sqrt(np.pi)*norm_X*norm_Z*att[2]
    sh_basis[:,8] = np.sqrt(15)/4/np.sqrt(np.pi)*(norm_X**2-norm_Y**2)*att[2]
    return sh_basis

In [15]:
sh_basis = SH_basis(normal)

In [16]:
sh_basis[0]

array([ 0.88622693, -0.        ,  0.        , -0.        ,  0.        ,
       -0.        , -0.24770796, -0.        ,  0.        ])

In [39]:
normals = [[1, 0, 0],
[0, 0, 1],
[-1, 0, 0],
[0, 0, -1]]
normals = np.reshape(normals, (-1, 3))

In [40]:
shs = SH_basis(normals)

In [32]:
shs

array([[ 0.88622693,  0.        ,  0.        ,  1.02332671,  0.        ,
         0.        , -0.24770796,  0.        ,  0.42904277],
       [ 0.88622693,  1.02332671,  0.        ,  0.        ,  0.        ,
         0.        , -0.24770796,  0.        , -0.42904277],
       [ 0.88622693,  0.        ,  0.        , -1.02332671, -0.        ,
         0.        , -0.24770796, -0.        ,  0.42904277],
       [ 0.88622693, -1.02332671,  0.        ,  0.        , -0.        ,
        -0.        , -0.24770796,  0.        , -0.42904277]])

In [44]:
for i in shs[3]:
    print(i)

0.8862269254527579
0.0
-1.0233267079464883
0.0
0.0
-0.0
0.49541591220075143
-0.0
0.0


In [75]:
'''
             (b)
              +
              |
              |
    ---------- ----------+ (a) (ref angle)
              |
              |
'''

def generate_2d_normals(begin_angle, end_angle, clockwise=True, num=10):
    arr = np.linspace(begin_angle, end_angle, num=num)
    sign = -1 if clockwise else 1
    pairs = []
    for i in arr:
        a = np.cos(i)
        b = np.sin(i) * sign
        pairs.append((a, b))
        
    return pairs
    

In [80]:
def generate_3d_normals(begin_angle, end_angle, clockwise=True, num=10, null_dim='y'):
    pairs = generate_2d_normals(begin_angle, end_angle, clockwise, num)
    result = []
    for a,b in pairs:
        if null_dim == 'y':
            result.append((a, 0, b))
        elif null_dim == 'x':
            result.append((0, a, b))
        elif null_dim == 'z':
            result.append((a, b, 0))
        else:
            raise Error('null_dim is ill defined')
    
    return np.reshape(result, (-1, 3))

In [87]:
normals = generate_3d_normals(0, np.pi, clockwise=True, num=2, null_dim='y')

In [88]:
normals

array([[ 1.0000000e+00,  0.0000000e+00, -0.0000000e+00],
       [-1.0000000e+00,  0.0000000e+00, -1.2246468e-16]])

In [89]:
shs = SH_basis(normals)

In [92]:
def write_sh_to_files(shs):
    for i, sh in enumerate(shs):
        
        f = open('~/workspace/test/haha_rotate_light_{:02d}.txt'.format(i), 'w')
        f.write(sh)
        f.close()

In [94]:
np.concatenate((normals, normals, normals))

array([[ 1.0000000e+00,  0.0000000e+00, -0.0000000e+00],
       [-1.0000000e+00,  0.0000000e+00, -1.2246468e-16],
       [ 1.0000000e+00,  0.0000000e+00, -0.0000000e+00],
       [-1.0000000e+00,  0.0000000e+00, -1.2246468e-16],
       [ 1.0000000e+00,  0.0000000e+00, -0.0000000e+00],
       [-1.0000000e+00,  0.0000000e+00, -1.2246468e-16]])